server:
  port: 30002
spring:
  application:
    name: c-client-parent
  datasource:
    url: jdbc:mysql://49.233.54.158:3306/translate?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: "http://49.233.54.158:8848"
      username: nacos
      password: nacos
fanyigou:
  appid: "1672147768795"
  secret: "14bf4dba099d8bef7d0beee887e117c96925ed8c"


#阿里云 OSS（配置bucket信息）
aliyun.:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com #地域节点
      keyid: LTAI5tGyvXA5eBioPbit1yXi      #ID
      keysecret: nKbRsqEkCukQpHToaj72TmFmlB6K6H #秘钥
      bucketname: translate-core #项目名称

mybatis:
  mapper-locations: classpath:mapper/*.xml